### ISSUE TITLE
2d canvas API?

### ISSUE THREAD

**Issue by af** [BuckleTypes/bs-webapi-incubator#55]
Hi,
I'm writing a simple 2d canvas game, and have been building up a bunch of bindings for the CanvasRenderingContext2D API. Would it be helpful to add them in a pull request here? If so, a couple of questions:

* There's an existing `ReasonJs.CanvasElement.getContext` function that takes a string, and returns a context. However the existing context API here is for WebGL, not the 2d API. So I'd propose changing this to `getWebGLContext`, and creating a new `get2dContext` function. It looks like `[@bs.as]` will work to pass the appropriate string parameter in to js's `getContext`

* ints or floats for canvas methods? I've been using floats myself but I'm wondering if there's a case for integer arguments

**Comment by glennsl** [comment]
Hi! I think that'd be a yes on all counts. Except perhaps the last one, where a "yes" wouldn't really make sense. There I guess I'd say to stick with floats until it's evident that ints would be much more convenient. Floats are pretty safe.

**Comment by glennsl** [comment]
Closing this since #56 has been merged, though it's not complete it's a very good start!
