### ISSUE TITLE
Should we drop the test script and just check in the test artifacts?

### ISSUE THREAD

**Issue by glennsl** [BuckleTypes/bs-webapi-incubator#57]
cc @chenglou 

Other than potentially forgetting to check in the rendered artifacts and not having it be caught by CI, do we really lose anything by not having a test script and the explicit "expected" snapshots, compared to just using checked in artifacts as snapshots and the review process to verify them? It might even be a win, since there would be more eyes on it.

**Comment by chenglou** [comment]
Yeah check the artifacts in!
