### ISSUE TITLE
bs-webapi-incubator not found in npm

### ISSUE THREAD

**Issue by rlucha** [BuckleTypes/bs-webapi-incubator#60]
Running `npm install bs-webapi-incubator` as in the README will fail.
The package is not present in the npm repository.

https://www.npmjs.com/search?q=bs-webapi-incubator

**Comment by glennsl** [comment]
Crap! That's why I shouldn't have "fixed" that, lol. I'lll make sure to publish a new version with the correct name shortly, in the meantime you can `npm install reason-js`

**Comment by glennsl** [comment]
Ok, I've published it as `bs-webapi` and updated the instructions to `npm install bs-webapi`. Thanks for reporting, and let us know if there's any further problems!
